services:
  - type: web
    name: ocr-topic-matcher
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LANG_PATH
        value: tessdata_fast
      - key: EXCEL_PATH
        value: DSA_Concept_Graph.xlsx
    buildFilter:
      paths:
        - package.json
        - tsconfig.json
        - render.yaml
        - src/**
        - DSA_Concept_Graph.xlsx
        - tessdata_fast/**
